databases:
  - name: skin-care-connect-db
    plan: free
    postgresMajorVersion: 16

services:
  - type: web
    name: skin-care-connect
    runtime: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "streamlit run src/app.py --server.port $PORT --server.address 0.0.0.0"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: DATABASE_URL
        fromDatabase:
          name: skin-care-connect-db
          property: connectionString
    healthCheckPath: /
